### ISSUE TITLE
Conda Installation Failure on Mac

### ISSUE THREAD

**Issue by rjp23** [MarcSkovMadsen/awesome-panel#59]
I assume I'm doing something wrong but I'm following the conda instructions here: https://awesome-panel.readthedocs.io/en/latest/_copy_of_project_root/README.html#getting-started-with-the-awesome-panel-repository

```
(awesome-panel) Robs-MBP:awesome-panel rob$ conda install --file requirements_local.txt
CondaValueError: could not parse '-r ./requirements.txt' in: requirements_local.txt
```

I also tried:
```
(awesome-panel) Robs-MBP:awesome-panel rob$ conda install --file requirements.txt
CondaValueError: could not parse '-r ./requirements_base.txt' in: requirements.txt
```

and:

```
(awesome-panel) Robs-MBP:awesome-panel rob$ conda install --file requirements_base.txt
CondaValueError: could not parse 'geopandas; platform_system != "Windows" # To `pip install geopandas` on windows please follow https://geoffboeing.com/2014/09/using-geopandas-windows/' in: requirements_base.txt
```

This was on a freshly installed miniconda setup on a Big Sur (11.6) mac.

**Comment by MarcSkovMadsen** [comment]
What error messages do you see?

**Comment by rjp23** [comment]
Those are the entire error message:

```
(awesome-panel) Robs-MBP:awesome-panel rob$ conda install --file requirements_local.txt
CondaValueError: could not parse '-r ./requirements.txt' in: requirements_local.txt
```

It seems there might be multiple problems with getting this working on a mac.

It installs an old version of nodejs which doesn't work. There's some issue with nodejs/conda on macs (as per https://stackoverflow.com/questions/62325068/cannot-install-latest-nodejs-using-conda-on-mac). I used the mamba method there to force a new version.

conda also fails to install pytorch as it doesn't find a compatible version. Doing that via pip install seems to install it but the app.py fails to run

```
2021-12-19 17:38:25,325 Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x7ffce021e610>: module 'torch.jit' has no attribute 'unused'
File 'inception.py', line 195, in Inception3:
@torch.jit.unused Traceback (most recent call last):
  File "/Users/rob/miniconda3/envs/awesome-panel/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/Users/rob/Work/awesome-panel/app.py", line 20, in <module>
    from application.pages import APP_ROUTES  # pylint: disable=unused-import
  File "/Users/rob/Work/awesome-panel/application/pages/__init__.py", line 29, in <module>
    from application.pages.detr import detr
  File "/Users/rob/Work/awesome-panel/application/pages/detr/detr.py", line 35, in <module>
    from application.pages.detr.model import (
  File "/Users/rob/Work/awesome-panel/application/pages/detr/model.py", line 7, in <module>
    import torchvision.transforms as T
  File "/Users/rob/miniconda3/envs/awesome-panel/lib/python3.7/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import models
  File "/Users/rob/miniconda3/envs/awesome-panel/lib/python3.7/site-packages/torchvision/models/__init__.py", line 5, in <module>
    from .inception import *
  File "/Users/rob/miniconda3/envs/awesome-panel/lib/python3.7/site-packages/torchvision/models/inception.py", line 63, in <module>
    class Inception3(nn.Module):
  File "/Users/rob/miniconda3/envs/awesome-panel/lib/python3.7/site-packages/torchvision/models/inception.py", line 195, in Inception3
    @torch.jit.unused
AttributeError: module 'torch.jit' has no attribute 'unused'
```
Sorry that's a list of problems for you! I'll likely just try this on our Linux HPC instead of trying on a mac.

**Comment by rjp23** [comment]
I finally tried this on our linux HPC and I get the same error

```
conda install --file requirements_local.txt
CondaValueError: could not parse '-r ./requirements.txt' in: requirements_local.txt
```

Is there something wrong with the syntax in your requirements files?
